In [1]:
# Add dependencies
import pandas as pd
import numpy as np

In [2]:
# load files
cost_attendance_df = pd.read_csv("Resources/cost-attendance.csv")
financial_aid_df = pd.read_csv("Resources/financial-aid.csv")
grad_rates_df = pd.read_csv("Resources/grad-rates.csv")
institutions_df = pd.read_csv("Resources/institutions.csv")
net_price_df = pd.read_csv("Resources/net-price.csv")
retention_rates_df = pd.read_csv("Resources/retention-rates.csv")

In [3]:
# Inspect Institutions
institutions_df.head()
# institutions_df.columns.to_list()
# len(institutions_df)
# institutions_df.dtypes

,UnitID,Institution Name,Institution name alias (HD2016),Street address or post office box (HD2016),City location of institution (HD2016),State abbreviation (HD2016),ZIP code (HD2016),Institution's internet website address (HD2016),Longitude location of institution (HD2016),Latitude location of institution (HD2016),...,Grand total (EF2016A All students Undergraduate total),American Indian or Alaska Native total (EF2016A All students Undergraduate total),Asian total (EF2016A All students Undergraduate total),Black or African American total (EF2016A All students Undergraduate total),Hispanic total (EF2016A All students Undergraduate total),Native Hawaiian or Other Pacific Islander total (EF2016A All students Undergraduate total),White total (EF2016A All students Undergraduate total),Two or more races total (EF2016A All students Undergraduate total),Race/ethnicity unknown total (EF2016A All students Undergraduate total),Nonresident alien total (EF2016A All students Undergraduate total)
0,180203,Aaniiih Nakoda College,,269 Blackfeet Avenue Agency,Harlem,MT,59526,www.ancollege.edu,-108.757816,48.484196,...,149.0,140.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0
1,222178,Abilene Christian University,,,Abilene,TX,79699,www.acu.edu,-99.709540,32.469150,...,3758.0,12.0,42.0,338.0,616.0,4.0,2402.0,185.0,10.0,149.0
2,138558,Abraham Baldwin Agricultural College,ABAC,2802 Moore Hwy,Tifton,GA,31793-2601,www.abac.edu,-83.528281,31.481889,...,3475.0,16.0,27.0,316.0,208.0,2.0,2808.0,45.0,0.0,53.0
3,488031,Abraham Lincoln University,,3530 Wilshire Boulevard Suite 1430,Los Angeles,CA,90010,www.alu.edu/,-118.301181,34.060990,...,25.0,0.0,4.0,3.0,4.0,1.0,5.0,1.0,7.0,0.0
4,172866,Academy College,,1600 W. 82nd Street Suite 100,Bloomington,MN,55431-1411,www.academycollege.edu,-93.299809,44.855722,...,116.0,1.0,11.0,14.0,4.0,0.0,73.0,2.0,11.0,0.0

In [24]:
# look at null values per column
institutions_df.isnull().sum()

UnitID                                                                                             0
Institution Name                                                                                   0
Institution name alias (HD2016)                                                                   33
Street address or post office box (HD2016)                                                        33
City location of institution (HD2016)                                                             33
State abbreviation (HD2016)                                                                       33
ZIP code (HD2016)                                                                                 33
Institution's internet website address (HD2016)                                                   33
Longitude location of institution (HD2016)                                                        33
Latitude location of institution (HD2016)                                                         33
Historically Black College or University (HD2016)                                                 33
Bureau of Economic Analysis (BEA) regions (HD2016)                                                33
Tribal college (HD2016)                                                                           33
Sector of institution (HD2016)                                                                    33
Control of institution (HD2016)                                                                   33
Percent admitted - total (DRVADM2016)                                                           2013
Grand total (EF2016  All students  Undergraduate total)                                           33
Total men (EF2016  All students  Undergraduate total)                                             33
Total women (EF2016  All students  Undergraduate total)                                           33
Grand total (EF2016A  All students  Undergraduate total)                                          33
American Indian or Alaska Native total (EF2016A  All students  Undergraduate total)               33
Asian total (EF2016A  All students  Undergraduate total)                                          33
Black or African American total (EF2016A  All students  Undergraduate total)                      33
Hispanic total (EF2016A  All students  Undergraduate total)                                       33
Native Hawaiian or Other Pacific Islander total (EF2016A  All students  Undergraduate total)      33
White total (EF2016A  All students  Undergraduate total)                                          33
Two or more races total (EF2016A  All students  Undergraduate total)                              33
Race/ethnicity unknown total (EF2016A  All students  Undergraduate total)                         33
Nonresident alien total (EF2016A  All students  Undergraduate total)                              33
dtype: int64

In [37]:
columns = ['Institution Name', 'Grand total (EF2016A  All students  Undergraduate total)']
clean_institutions_df = institutions_df.dropna(subset=columns)
clean_institutions_df.head()
len(clean_institutions_df)

3810

In [29]:
clean_institutions_df.isnull().sum()

UnitID                                                                                             0
Institution Name                                                                                   0
Institution name alias (HD2016)                                                                    0
Street address or post office box (HD2016)                                                         0
City location of institution (HD2016)                                                              0
State abbreviation (HD2016)                                                                        0
ZIP code (HD2016)                                                                                  0
Institution's internet website address (HD2016)                                                    0
Longitude location of institution (HD2016)                                                         0
Latitude location of institution (HD2016)                                                          0
Historically Black College or University (HD2016)                                                  0
Bureau of Economic Analysis (BEA) regions (HD2016)                                                 0
Tribal college (HD2016)                                                                            0
Sector of institution (HD2016)                                                                     0
Control of institution (HD2016)                                                                    0
Percent admitted - total (DRVADM2016)                                                           1980
Grand total (EF2016  All students  Undergraduate total)                                            0
Total men (EF2016  All students  Undergraduate total)                                              0
Total women (EF2016  All students  Undergraduate total)                                            0
Grand total (EF2016A  All students  Undergraduate total)                                           0
American Indian or Alaska Native total (EF2016A  All students  Undergraduate total)                0
Asian total (EF2016A  All students  Undergraduate total)                                           0
Black or African American total (EF2016A  All students  Undergraduate total)                       0
Hispanic total (EF2016A  All students  Undergraduate total)                                        0
Native Hawaiian or Other Pacific Islander total (EF2016A  All students  Undergraduate total)       0
White total (EF2016A  All students  Undergraduate total)                                           0
Two or more races total (EF2016A  All students  Undergraduate total)                               0
Race/ethnicity unknown total (EF2016A  All students  Undergraduate total)                          0
Nonresident alien total (EF2016A  All students  Undergraduate total)                               0
dtype: int64